services:
  - type: web
    name: resume-optimizer
    env: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn wsgi:app
    healthCheckPath: /api/health
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8080
    disk:
      name: uploads
      mountPath: /tmp/uploads
      sizeGB: 1
    domains:
      - resume-optimizer-api.onrender.com  # Default domain 