services:
  - type: web
    name: resume-optimizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --log-level info
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8080
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PDF_GENERATION_MODE
        value: fallback
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /tmp/uploads
      sizeGB: 1
    domains:
      - resume-optimizer-api.onrender.com  # Default domain 